import naive_bayes

documents = naive_bayes.load_dataset('F:/other/py/NLPExtractor/out')
print("load dataset finish")
prob_class,likelihood = naive_bayes.train_naive_bayes(documents)
print("train_naive_bayes finish")
naive_bayes.save_model("naive_bayes.model",prob_class,likelihood)
print("save_model finish")
model = naive_bayes.load_model("naive_bayes.model")
print("load_model finish")
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/体育/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/财经/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/彩票/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/房产/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/股票/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/教育/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/家居/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/科技/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/社会/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/时尚/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/时政/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/游戏/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/星座/test_set"),model))
print(naive_bayes.predict_naive_bayes(naive_bayes.test_naive_bayes("F:/other/py/NLPExtractor/out/娱乐/test_set"),model))
